### ISSUE TITLE
EE6

### ISSUE THREAD

**Issue by roberthallatt** [croxton/Mustash#14]
Hi,

I installed the EE6 version to test it out and noticed that when I try to go to the settings panel, the following exception is thrown:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cpsca_7.exp_member_groups' doesn't exist:
SELECT `group_id`, `group_title` FROM (`exp_member_groups`) WHERE `group_id` NOT IN (1, 2, 3, 4) ORDER BY `group_title` asc

Apart form that, the only other issue I see is a mis-aligned search input field on the variables page.

When do you think this will be officially released? i have several sites that use the add-on.

Rob

**Comment by roberthallatt** [comment]
Update: So for some reason, some tables went missing. I restored them and everything is working fine now.

**Comment by croxton** [comment]
Things work, it's mostly a case of making the screens follow the new EE6 UI (as you have seen). No firm release data but I'll continue to work on this in my spare time.

**Comment by roberthallatt** [comment]
Thanks Mark. I’m a big fan of your extensions and currently use them for our highest profile sites.

https://www.cps.ca
https://www.caringforkids.cps.ca

The use the design pattern on the Stash Wiki site.

From: Mark Croxton ***@***.***>
Reply-To: croxton/Mustash ***@***.***>
Date: Thursday, March 25, 2021 at 10:16 AM
To: croxton/Mustash ***@***.***>
Cc: Robert Hallatt ***@***.***>, Author ***@***.***>
Subject: Re: [croxton/Mustash] EE6 (#14)


Things work, it's mostly a case of making the screens follow the new EE6 UI (as you have seen). No firm release date but I'll continue to work on this in my spare time.

**Comment by croxton** [comment]
I'm delighted that my add-ons have helped, and for such a great cause too!
